### ISSUE TITLE
Spellcheck failure for camel cased words

### ISSUE THREAD

**Issue by pgarus97** [devonfw/solicitor#129]
### Expected behavior

The spellcheck.yml action should check if the documentation is written without spelling errors based on dictionary files.

### Actual behavior

The action fails every time due to words in camelCase not being recognized properly. The solicitor.dict dictionary file does not contain al camelCase occurences. A global solution to avoid words in camel case should be created.

**Comment by ohecker** [comment]
Fixed with the above mentioned PR
