### ISSUE TITLE
solicitor_licenseinfo.html of v1.12.0 is missing (at least) two license texts

### ISSUE THREAD

**Issue by ohecker** [devonfw/solicitor#187]
The generated license info file of Solicitor itself is missing at least two license texts.

![image](https://github.com/devonfw/solicitor/assets/8004361/2e766964-a66f-46d6-9c57-ce4cdabffc75)

This needs to be corrected.

**Comment by duph97** [comment]
Error occured between release 1.3.0 and 1.4.0

02.June.2022
- https://github.com/devonfw/solicitor/commit/29ad70bd7fb4ad7f9c0df4a754ee799c027a0412
- Two new dependencies added into pom.xml
- These probably contain _xml-apis/xml-apis/1.4.01_ as third party dependency, which is licensed under SAX-PD and W3C
- In _test/resources/licenses_ the two new licenses were not added.
