### ISSUE TITLE
Additional Solicitor Lifecycle Method

### ISSUE THREAD

**Issue by duph97** [devonfw/solicitor#208]
As a developer, I want to have an additional lifecycle method, so that I can apply changes before the reports are generated but after the rules have been processed.
Currently there are two lifecycle methods.

- void modelRootInitialized(ModelRoot modelRoot);
- void endOfMainProcessing(ModelRoot modelRoot);

The additional method could be 
- void beforeWriterProcessing(ModelRoot modelRoot);

**Comment by ohecker** [comment]
I renamed/moved the new method:
- afterModelProcessing()

I also added another method which might be useful:
- afterReadingInventory()

**Comment by ohecker** [comment]
Merged. Close.
