### ISSUE TITLE
Update Solicitor to recent versions of used frameworks/libraries

### ISSUE THREAD

**Issue by duph97** [devonfw/solicitor#218]
As a person responsible for Solicitor I want to ensure that Solicitor does not use outdated dependencies which might

- impose unnecessary risks due to known and (in later versions) already fixed security issues
- impose increased cost for upgrading of dependencies to newer versions.

Therefore all dependencies of Solicitor should be updated to recent versions of their dependencies.

**Comment by ohecker** [comment]
reviewed, merged, close.
