### ISSUE TITLE
Recently introduced fields in datamodel are missing in ModelImporterExporter 

### ISSUE THREAD

**Issue by ohecker** [devonfw/solicitor#234]
This results in these fields to be not correctly read from persisted data model files and  e.g. always be reported as "changed" when delta processing is done.

Handling seems to be missing for at least:
- dataStatus
- traceabilityNotes
- sourceDownloadUrl
- packageDownloadUrl
- noticeFileContent
- declaredLicenseContent

The ModelImporterExporter needs to be corrected to also handle these fields.

**Comment by mahmoudAlkam** [comment]
Pull request under https://github.com/devonfw/solicitor/pull/236
