### ISSUE TITLE
CSV Reader does not create a packageURL

### ISSUE THREAD

**Issue by duph97** [devonfw/solicitor#274]
The CSV reader in Solicitor does not create a packageURL. Without a packageURL you cannot use services that depend on this value. This must be fixed.

Proposed solution:

1. The package type is added as csv reader configuration property on top level
1. package type can be of any purl supported value
1. packageURL in `appComponent` is only set, if a PackageURLHandler exists for that type

Hints:

* Supported pURL Types: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst
* packageType is kind of similar to the `repoType`
* Validation whether a purl type is supported is also implemented in the CycloneDX reader

**Comment by ohecker** [comment]
Merged -> Close
