### ISSUE TITLE
Incorrect detection of EDL 1.0 as BSD-3 clause

### ISSUE THREAD

**Issue by maybeec** [devonfw/solicitor#47]
### Expected behavior

As a user, I want generate a license report for my product containing https://mvnrepository.com/artifact/javax.persistence/javax.persistence-api/2.2 so that I get an export showing the license of the product.

### Actual behavior

The maven project is exported with the following row:

javax.persistence-api | javax.persistence | 2.2 | BSD-3-Clause | http://www.eclipse.org/org/documents/edl-v10.php
-- | -- | -- | -- | -- | --

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Include javax.persistence-api in a maven project
2. run solicitor and see the html report

### Affected version:

* OS: Windows

**Comment by ohecker** [comment]
The observed behaviour is intended in this way and is IMHO correct.

The EDL1.0 is a BSD-3-Clause License. See the following references:

Statement of SPDX why EDL1.0 was not added to the SPDX license list:

https://wiki.spdx.org/view/Legal_Team/License_List/Licenses_Under_Consideration:

> ...
> See http://www.eclipse.org/org/documents/edl-v10.php
> ...
> **However, the license text is the same as the SPDX BSD-3-Clause, which allows for variations in Year and Owner, so it is already covered by that license and there is no need to add this one.**  
> ...

And from the license page of Eclipse itself:

https://www.eclipse.org/org/documents/edl-v10.php
> ...
> OSI Approved
> **The Eclipse Distribution License is an OSI Approved Open Source License by means of the [New BSD License](https://opensource.org/licenses/BSD-3-Clause).** 
> ...
