### ISSUE TITLE
Add multiple technologies for Download Script

### ISSUE THREAD

**Issue by flohden** [devonfw/solicitor#48]
For different technologies, like maven oder npm we need to download the package from different technologies. 
For example in Java (with maven) we download the Libraries from mavenrepository.com and in Angular/Node.js and other technologies based on Javascript (with NPM) we download from npmjs.org. 
But if there are multiple technologies in one project, we can't just download from one repository. 
We need to distinguish this between the technologies to download for  and need a change in the DataModel for this like a repoType. This RepoType will be given in the config. We write in another column from which type of repository we have to download and distiguish this in the velocity script to download from the right repository.

**Comment by ohecker** [comment]
PR #50 merged. This closes this enhancement.
