### ISSUE TITLE
Normalizing the URL for Github resources

### ISSUE THREAD

**Issue by duph97** [devonfw/solicitor#75]
Currently only the URL which is declared in the input file is used to fetch the license information. 
This URL is in many cases broken. For example the content behind the URL is sometimes in html format instead of raw text.
The URL should be normalized until it points to a resource, which contains the license information in clean, readable text format.
This automation is possible for Github links.

**Comment by duph97** [comment]
Expand Data Model for WebContentProvider

In addition to the URL and the webcontent, the following attributes should be added which contain useful information.

- An effective URL, which is the URL after normalization, should be a valid URL which is used by solicitor to fetch the license information. Currently only the URL, declared in the input file, is shown in the Acknowledgement file. This URL is in many cases broken.
- A trace, which allows the user to comprehend the steps leading to the effective URL. The trace should contain all the URLs which were tested in the normalization process.

**Comment by ohecker** [comment]
Closed with https://github.com/devonfw/solicitor/pull/90
